[theme]
primaryColor="#5c0101"
backgroundColor="#c8a8c8"
secondaryBackgroundColor="#606d98"
textColor="#0e0000"
font="sans serif"[theme]
primaryColor="#5c0101"
backgroundColor="#c8a8c8"
secondaryBackgroundColor="#606d98"
textColor="#0e0000"
font="sans serif"
